-- Column name	Type	Nullable
-- ID	INTEGER	FALSE
-- FISH_TYPE	INTEGER	FALSE
-- LENGTH	FLOAT	TRUE
-- TIME	DATE	FALS


SELECT 
    TIME, 
    COUNT(ID) AS CATCH_COUNT, 
    SUM(LENGTH) AS TOTAL_LENGTH
FROM FISH_INFO

GROUP BY 
    TIME